apiVersion: v1
kind: Secret
metadata:
  name: edutrack-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://Shashank_Shetgeri:Admin12345@cluster0.mhg7dnk.mongodb.net/student_marks?retryWrites=true&w=majority&appName=Cluster0"
  SESSION_SECRET: "your-k8s-session-secret-key"
